spring:
  config:
    activate:
      on-profile: docker

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/appdb
    username: appuser
    password: apppassword

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://appuser:apppassword@mongodb:27017/appdb?authSource=admin

  # Redis Configuration
    redis:
      host: redis
      port: 6379

# Kafka Configuration
kafka:
  bootstrap-servers: kafka:29092
